---
title: "demandFillR"
author: "Jason Corderoy"
date: "2024-11-13"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(testthat)
source("R/solver.r")
```

## Fill that demand

A simple minimalistic library for demand filling.

Of course there are fancy solves like OR tools but most the time you just need something simple and that can be quickly/easily tinkered to solve for what your personal needs are.

```{r cars}
# Check 1st solve is non as good as later solves in this specific case
solved <- matrix(rep(0, 3*4), ncol = 3, byrow = T)
options <- matrix(c(2, 0, 0, 1, 1, 0, 1, 0, 1), ncol = 3, byrow = T)
demand <- c(4, 2, 2)
dfw <- c(10, 1, 1) # loves the 1st one
dew <- c(-10, -0.5, -0.5) # once 1st options demand exceeded it is heavily penalized
expect1 <- matrix(c(2, 0, 0, 2, 0, 0, 1, 1, 0, 1, 1, 0),
                 ncol = 3,
                 byrow = T)
expect2 <- matrix(c(1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0),
                  ncol = 3,
                  byrow = T)
for (i in 1:4) {
  solved <- xsolve(
    solved = solved,
    options = options,
    demand = demand,
    dfw = dfw,
    dew = dew
  )
}
solved1 <- solved
expect_identical(solved1, expect1)

print(solved1)
print(expect1)
print(colSums(expect1))
print(demand)

for (i in 1:4) {
  solved <- xsolve(
    solved = solved,
    options = options,
    demand = demand,
    dfw = dfw,
    dew = dew
  )
}
solved2 <- solved
expect_identical(solved2, expect2)

print(solved2)
print(expect2)
print(colSums(expect2))
print(demand)

```

